language: python
cache: apt
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# TODO: findout howto install system libcares...
before_install:
  - sudo apt-get update
  - sudo apt-get --reinstall install libc-ares-dev
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
  - python setup.py install
  - pip install tox
script:
  - ./tests.py
  - tox
