language: python
cache: apt
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# TODO: findout howto install system libcares...
before_install:
  - sudo apt-get update
  - sudo apt-get install -qq -t '1.10*' libc-ares2 libc-ares-dev
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - pip install flake8
  - pip install mccabe
  - python setup.py build_ext --use-system-libcares
  - python setup.py install
  - python setup.py build_ext
  - python setup.py install
    #  - pip install tox
script:
  - ./tests.py
    #  - tox
