language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# TODO: findout howto install system libcares...
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-sphinx
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
  - python setup.py install
script:
  - ./tests.py
  - cd docs/; sphinx-build -nW -b html -d _build/doctrees . _build/html
