language: python
cache: apt
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# TODO: findout howto install system libcares...
#before_install:
#  # travis ci on 2014-12-27 -> ubuntu 12.04 doesn't contain the libc-ares2 version 1.10.0 - sigh
#  - sudo apt-get update
#  - sudo apt-get install -qq -t '1.10*' libc-ares2 libc-ares-dev
env:
#  - TOX_ENV=py26
#  - TOX_ENV=py27
#  - TOX_ENV=py32
#  - TOX_ENV=py33
#  - TOX_ENV=py34
  - TOX_ENV=python
  - TOX_ENV=flake8
install:
  - if [[ $TOX_ENV == 'python' && $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - if [[ $TOX_ENV == 'python' && $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install nosetest; fi
  - if [[ $TOX_ENV == 'flake8' ]]; then pip install flake8; fi
  - if [[ $TOX_ENV == 'flake8' ]]; then pip install mccabe; fi
  - pip install tox
#  - if [[ $TOX_ENV == 'python' ]]; then python setup.py build_ext --use-system-libcares; fi
#  - if [[ $TOX_ENV == 'python' ]]; then python setup.py install; fi
  - if [[ $TOX_ENV == 'python' ]]; then python setup.py build_ext; fi
  - if [[ $TOX_ENV == 'python' ]]; then python setup.py install; fi
script:
  - if [[ $TOX_ENV == 'python' ]]; then ./tests.py; fi
  - if [[ $TOX_ENV == 'python' && $TRAVIS_PYTHON_VERSION == '2.6' ]]; then tox -e py26; else tox -e $TOX_ENV; fi
